AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  step-funtions

  Sample SAM Template for step-funtions

Resources:

  Hello1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello1/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - S3WritePolicy:
            BucketName: local-test-demo-bucket


  Hello2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello2/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 20
      Policies:
        - S3ReadPolicy:
            BucketName: local-test-demo-bucket
      

  HelloStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/hello.asl.json
      DefinitionSubstitutions:
        Hello1FunctionArn: !GetAtt Hello1.Arn
        Hello2FunctionArn: !GetAtt Hello2.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref Hello1
        - LambdaInvokePolicy:
            FunctionName: !Ref Hello2
