AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  step-funtions

  Sample SAM Template for step-funtions

Globals:
  Function:
    MemorySize: 512
    Timeout: 25    

Resources:

  Hello1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello1/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - S3WritePolicy:
            BucketName: local-test-demo-bucket


  Hello2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello2/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - S3ReadPolicy:
            BucketName: local-test-demo-bucket
  
  Hello2Java:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello2_java/
      Handler: example.Handler::handleRequest
      Runtime: java8
      Policies:
        - S3ReadPolicy:
            BucketName: local-test-demo-bucket
      

  HelloStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/hello.asl.json
      DefinitionSubstitutions:
        Hello1FunctionArn: !GetAtt Hello1.Arn
        Hello2FunctionArn: !GetAtt Hello2.Arn
        Hello3FunctionArn: !GetAtt Hello2Java.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref Hello1
        - LambdaInvokePolicy:
            FunctionName: !Ref Hello2
        - LambdaInvokePolicy:
            FunctionName: !Ref Hello2Java
