AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-dynamodb-mapper

  Sample SAM Template for java-dynamodb-mapper

Resources:
  StatusApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: APIGateway for Status Endpoint
      StageName: Staging

  GetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.GetAll::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: Status
      Events:
        GetAllApi:
          Type: Api
          Properties:
            RestApiId: !Ref StatusApiGateway
            Path: /status
            Method: GET

  CreateOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.CreateOne::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 10
      Policies:
        - DynamoDBWritePolicy:
            TableName: Status
  UpdateOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.UpdateOne::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: Status
        - DynamoDBWritePolicy:
            TableName: Status
