AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'upload-to-s3-poc

  Sample SAM Template for upload-to-s3-poc

  '
Globals:
  Function:
    Timeout: 3
Resources:
  MyApi:
    Type: AWS::Serverless::HttpApi
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://yimeng-test-bucket1/3a49005f38c1b1b3e14e31d5911578e2
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3UploadBucket
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
            ApiId:
              Ref: MyApi
  S3UploadBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: yimeng-test-bucket2
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - POST
          - HEAD
          AllowedOrigins:
          - '*'
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
