AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-logger

  Sample SAM Template for java-logger

Globals:
  Function:
    Timeout: 20

Resources:
  LoggerFunctionWARN:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          LOG_LEVEL: WARN
  LoggerFunctionDEBUG:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          LOG_LEVEL: DEBUG